#!/usr/bin/env bash
# doctrine-lint — assert docs/doctrine/doctrine-manifest.yaml is the single source of truth
# and that doctrine cross-links don't rot. Pure bash + coreutils, ZERO runtime deps.
#
#   Run:  bash docs/scripts/doctrine-lint.sh    (also fired by .hooks/pre-commit and CI)
#
# Rules:
#   1. Coverage  — every docs/doctrine/*-doctrine.md is registered in the manifest.
#   2. Existence — every entry's path exists and matches docs/doctrine/<id>-doctrine.md.
#   3. Pointers  — every pointers[] file exists AND links to the doctrine (rename-rot guard).
#   4. Skills    — IF managed ambient stubs exist under .claude/skills/doctrine-*/
#                  (written by doctrine-skills-sync.sh), they mirror the manifest 1:1.
#                  Zero managed stubs → silent pass (feature not adopted).

set -u

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
MANIFEST="$ROOT/docs/doctrine/doctrine-manifest.yaml"
DOCTRINE_DIR="$ROOT/docs/doctrine"

[ -f "$MANIFEST" ] || { echo "doctrine-lint: manifest not found at $MANIFEST" >&2; exit 1; }

errors=0
errmsgs=""
fail() { errmsgs="${errmsgs}  ✗ $1"$'\n'; errors=$((errors + 1)); }

registered=" "   # space-delimited set of registered basenames
registered_ids=" "   # space-delimited set of registered ids (rule 4)
count=0

# Validate one accumulated entry (id / path / space-separated pointers).
validate() {
  local id="$1" path="$2" pointers="$3" base p
  [ -n "$id" ] || return 0
  count=$((count + 1))
  if [ -z "$path" ]; then fail "entry '$id': missing path"; return; fi
  base=$(basename "$path")
  registered="${registered}${base} "
  registered_ids="${registered_ids}${id} "
  [ "$base" = "$id-doctrine.md" ] || \
    fail "entry '$id': path $path should be docs/doctrine/$id-doctrine.md"
  if [ ! -f "$ROOT/$path" ]; then fail "entry '$id': path does not exist: $path"; return; fi
  for p in $pointers; do
    if [ ! -f "$ROOT/$p" ]; then fail "entry '$id': pointer file missing: $p"; continue; fi
    grep -qF -- "$base" "$ROOT/$p" || \
      fail "entry '$id': $p should link to $base but doesn't (rename-rot?)"
  done
}

cur_id="" cur_path="" cur_pointers=""
while IFS= read -r raw || [ -n "$raw" ]; do
  line="${raw%%#*}"                                   # strip comments
  line="${line%"${line##*[![:space:]]}"}"             # strip trailing whitespace
  [ -n "$line" ] || continue
  if [[ "$line" =~ ^[[:space:]]*-[[:space:]]+id:[[:space:]]*(.+)$ ]]; then
    validate "$cur_id" "$cur_path" "$cur_pointers"    # flush previous entry
    cur_id="${BASH_REMATCH[1]}"; cur_path=""; cur_pointers=""
  elif [[ "$line" =~ ^[[:space:]]+path:[[:space:]]*(.+)$ ]]; then
    cur_path="${BASH_REMATCH[1]}"
  elif [[ "$line" =~ ^[[:space:]]+pointers:[[:space:]]*\[(.*)\][[:space:]]*$ ]]; then
    cur_pointers="${BASH_REMATCH[1]//,/ }"
  fi
done < "$MANIFEST"
validate "$cur_id" "$cur_path" "$cur_pointers"        # flush last entry

# Rule 1 — coverage
for f in "$DOCTRINE_DIR"/*-doctrine.md; do
  [ -e "$f" ] || continue
  b=$(basename "$f")
  case "$registered" in
    *" $b "*) ;;
    *) fail "coverage: $b exists but is not registered in docs/doctrine/doctrine-manifest.yaml" ;;
  esac
done

# Rule 4 — ambient skill stubs (doctrine-skills-sync.sh) mirror the manifest.
# Only enforced once the feature is in use: zero MANAGED stubs → silent pass, so
# repos adopted before the feature stay green until they opt in.
SKILLS_DIR="$ROOT/.claude/skills"
SYNC_MARKER="auto-generated by docs/scripts/doctrine-skills-sync.sh"
managed_ids=" "
managed_count=0
for d in "$SKILLS_DIR"/doctrine-*/; do
  [ -d "$d" ] || continue
  s="${d}SKILL.md"
  [ -f "$s" ] && grep -qF -- "$SYNC_MARKER" "$s" || continue   # unmanaged files are none of our business
  managed_count=$((managed_count + 1))
  sid="$(basename "$d")"; sid="${sid#doctrine-}"
  managed_ids="${managed_ids}${sid} "
  case "$registered_ids" in
    *" $sid "*)
      # Stub must point at the id's doctrine file (rename-rot guard, same as rule 3).
      grep -qF -- "$sid-doctrine.md" "$s" || \
        fail "skills: .claude/skills/doctrine-$sid/SKILL.md does not reference $sid-doctrine.md — re-run docs/scripts/doctrine-skills-sync.sh"
      ;;
    *) fail "skills: managed stub doctrine-$sid has no manifest entry — re-run docs/scripts/doctrine-skills-sync.sh" ;;
  esac
done
if [ "$managed_count" -gt 0 ]; then
  for rid in $registered_ids; do
    case "$managed_ids" in
      *" $rid "*) ;;
      *) fail "skills: manifest entry '$rid' has no ambient stub at .claude/skills/doctrine-$rid/ — re-run docs/scripts/doctrine-skills-sync.sh" ;;
    esac
  done
fi

if [ "$errors" -gt 0 ]; then
  echo "doctrine-lint: $errors problem(s):" >&2
  printf '%s' "$errmsgs" >&2
  exit 1
fi
extra=""
[ "$managed_count" -gt 0 ] && extra=", $managed_count ambient stub(s) in sync"
echo "doctrine-lint: ok — $count doctrines registered, all paths + pointers resolve${extra}."
