#!/usr/bin/env bash
# doctrine-skills-sync — generate ambient doctrine-pointer skills from the manifest.
# Pure bash + coreutils, ZERO runtime deps (same contract as doctrine-lint.sh).
#
#   Run:  bash docs/scripts/doctrine-skills-sync.sh
#
# For every entry in docs/doctrine/doctrine-manifest.yaml this writes a thin
# Claude Code project skill at .claude/skills/doctrine-<id>/SKILL.md whose
# description (always in a session's context) carries the doctrine's summary +
# triggers, and whose body is a POINTER to the doctrine file — never a copy.
# That makes doctrine ambient: any session working in the doctrine's scope can
# self-load it via ordinary skill selection, without an orchestrator in the loop.
#
# Sync semantics (idempotent):
#   - manifest entry            → stub written/updated (only if content changed)
#   - entry removed             → its MANAGED stub is deleted
#   - a NON-managed file at a target path → hard error; we never overwrite
#     hand-written skills (fail fast, fix the collision by hand)
#
# "Managed" means the stub carries the MARKER line below. Files without it are
# never written to and never deleted. Parity between managed stubs and the
# manifest is enforced by doctrine-lint.sh (rule 4).

set -u

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
MANIFEST="$ROOT/docs/doctrine/doctrine-manifest.yaml"
SKILLS_DIR="$ROOT/.claude/skills"
MARKER="auto-generated by docs/scripts/doctrine-skills-sync.sh"

[ -f "$MANIFEST" ] || { echo "doctrine-skills-sync: manifest not found at $MANIFEST" >&2; exit 1; }

errors=0
fail() { echo "  ✗ $1" >&2; errors=$((errors + 1)); }

seen_ids=" "     # space-delimited set of manifest ids
wrote=0 unchanged=0 removed=0

# Render + write one stub from an accumulated entry (id / path / summary / triggers).
emit() {
  local id="$1" path="$2" summary="$3" triggers="$4"
  [ -n "$id" ] || return 0
  seen_ids="${seen_ids}${id} "

  if [ -z "$path" ]; then fail "entry '$id': missing path — stub skipped"; return; fi
  if [ -z "$summary" ]; then summary="Project doctrine '$id'."; fi

  local hint=""
  [ -n "$triggers" ] && hint=" Load before work involving: ${triggers}."

  local dir="$SKILLS_DIR/doctrine-$id"
  local file="$dir/SKILL.md"

  # Never clobber a hand-written skill occupying our target path.
  if [ -f "$file" ] && ! grep -qF -- "$MARKER" "$file"; then
    fail "collision: $file exists but is not managed by this script — move or delete it, then re-run"
    return
  fi

  # Escape double quotes so the YAML description stays a valid quoted scalar.
  local desc="${summary}${hint} (Doctrine pointer — auto-generated from docs/doctrine/doctrine-manifest.yaml.)"
  desc=${desc//\"/\\\"}

  local content
  content=$(cat <<EOF
---
name: doctrine-$id
description: "$desc"
---

<!-- $MARKER — do not edit.
     Source of truth: docs/doctrine/doctrine-manifest.yaml + $path
     Regenerate: bash docs/scripts/doctrine-skills-sync.sh -->

Read \`$path\` in full before continuing, then follow its Binding Rules for all
work in this session that touches its scope. If the doctrine contradicts the
code you find, fix the doctrine in the same change (agents-doctrine.md §2) —
never silently work around it.
EOF
)

  if [ -f "$file" ] && [ "$(cat "$file")" = "$content" ]; then
    unchanged=$((unchanged + 1))
    return
  fi
  mkdir -p "$dir"
  printf '%s\n' "$content" > "$file"
  wrote=$((wrote + 1))
  echo "  ✚ wrote .claude/skills/doctrine-$id/SKILL.md"
}

# ── Manifest parse ───────────────────────────────────────────────────────────
# Handles both shapes in the wild: single-line `summary: text` and folded
# `summary: >` blocks; inline `triggers: [a, b]` and block `- item` lists.
cur_id="" cur_path="" cur_summary="" cur_triggers="" mode=""
while IFS= read -r raw || [ -n "$raw" ]; do
  line="${raw%%#*}"                                   # strip comments
  line="${line%"${line##*[![:space:]]}"}"             # strip trailing whitespace
  [ -n "$line" ] || continue

  if [[ "$line" =~ ^[[:space:]]*-[[:space:]]+id:[[:space:]]*(.+)$ ]]; then
    emit "$cur_id" "$cur_path" "$cur_summary" "$cur_triggers"
    cur_id="${BASH_REMATCH[1]}"; cur_path=""; cur_summary=""; cur_triggers=""; mode=""
  elif [[ "$line" =~ ^[[:space:]]+path:[[:space:]]*(.+)$ ]]; then
    cur_path="${BASH_REMATCH[1]}"; mode=""
  elif [[ "$line" =~ ^[[:space:]]+summary:[[:space:]]*\>[-]?[[:space:]]*$ ]]; then
    mode="summary"                                    # folded block follows
  elif [[ "$line" =~ ^[[:space:]]+summary:[[:space:]]*(.+)$ ]]; then
    cur_summary="${BASH_REMATCH[1]}"; mode=""
  elif [[ "$line" =~ ^[[:space:]]+triggers:[[:space:]]*\[(.*)\][[:space:]]*$ ]]; then
    cur_triggers="${BASH_REMATCH[1]}"; mode=""
  elif [[ "$line" =~ ^[[:space:]]+triggers:[[:space:]]*$ ]]; then
    mode="triggers"                                   # block list follows
  elif [[ "$line" =~ ^[[:space:]]+[a-z-]+:[[:space:]] ]] || [[ "$line" =~ ^[[:space:]]+[a-z-]+:$ ]]; then
    mode=""                                           # any other field ends a block
  elif [ "$mode" = "triggers" ] && [[ "$line" =~ ^[[:space:]]+-[[:space:]]*(.+)$ ]]; then
    cur_triggers="${cur_triggers:+$cur_triggers, }${BASH_REMATCH[1]}"
  elif [ "$mode" = "summary" ]; then
    item="${line#"${line%%[![:space:]]*}"}"           # strip leading whitespace
    cur_summary="${cur_summary:+$cur_summary }$item"
  fi
done < "$MANIFEST"
emit "$cur_id" "$cur_path" "$cur_summary" "$cur_triggers"

# ── Sweep: remove managed stubs whose id left the manifest ───────────────────
for d in "$SKILLS_DIR"/doctrine-*/; do
  [ -d "$d" ] || continue
  s="${d}SKILL.md"
  [ -f "$s" ] && grep -qF -- "$MARKER" "$s" || continue    # never touch unmanaged files
  base=$(basename "$d")
  id="${base#doctrine-}"
  case "$seen_ids" in
    *" $id "*) ;;
    *)
      rm -r "$d"
      removed=$((removed + 1))
      echo "  − removed .claude/skills/$base/ (no longer in manifest)"
      ;;
  esac
done

if [ "$errors" -gt 0 ]; then
  echo "doctrine-skills-sync: $errors problem(s) — see above" >&2
  exit 1
fi
echo "doctrine-skills-sync: ok — $wrote written, $unchanged unchanged, $removed removed."
